name: Spec2Mol
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.2.25=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.16=h5eee18b_0
  - pip=25.0=py39h06a4308_0
  - python=3.9.21=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.8.0=py39h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.45.1=py39h06a4308_0
  - xz=5.6.4=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - about-time==4.2.1
      - absl-py==2.3.0
      - accelerate==1.7.0
      - addict==2.4.0
      - aimsim-core==2.2.2
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.0
      - aiosignal==1.3.2
      - alembic==1.15.2
      - alive-progress==3.2.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - ase==3.25.0
      - astartes==1.3.1
      - asttokens==3.0.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - autograd==1.8.0
      - babel==2.17.0
      - beautifulsoup4==4.13.4
      - bleach==6.2.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - chardet==5.2.0
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cma==4.2.0
      - colorlog==6.9.0
      - comm==0.2.2
      - contourpy==1.3.0
      - cycler==0.12.1
      - datamol==0.12.5
      - datasets==3.6.0
      - debugpy==1.8.14
      - decorator==5.2.1
      - defusedxml==0.7.1
      - deprecated==1.2.18
      - dill==0.3.8
      - docker-pycreds==0.4.0
      - dropout-layer-norm==0.1
      - dscribe==2.1.1
      - einops==0.8.1
      - eval-type-backport==0.2.2
      - evaluate==0.4.3
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.13.1
      - flash-attn==2.7.4.post1
      - fonttools==4.57.0
      - fqdn==1.5.1
      - frozenlist==1.6.0
      - fsspec==2024.6.1
      - gitdb==4.0.12
      - gitpython==3.1.44
      - grapheme==0.6.0
      - greenlet==3.2.0
      - grpcio==1.72.1
      - h11==0.14.0
      - h5py==3.13.0
      - httpcore==1.0.8
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - idna==3.10
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - ipykernel==6.29.5
      - ipython==8.18.1
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.4.2
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.4.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - lightning-utilities==0.14.3
      - llvmlite==0.43.0
      - loguru==0.7.3
      - mako==1.3.10
      - markdown==3.8
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - memory-profiler==0.61.0
      - mhfp==1.9.6
      - mistune==3.1.3
      - mordredcommunity==2.0.6
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.4.4
      - multiprocess==0.70.16
      - narwhals==1.44.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.4
      - notebook-shim==0.2.4
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - omegaconf==2.3.0
      - optuna==4.3.0
      - overrides==7.7.0
      - packaging==25.0
      - padelpy==0.1.14
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.2.1
      - platformdirs==4.3.7
      - plotly==6.1.2
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.1
      - protobuf==6.31.0
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==20.0.0
      - pycparser==2.22
      - pydantic==2.11.5
      - pydantic-core==2.33.2
      - pygments==2.19.1
      - pymoo==0.6.1.5
      - pyparsing==3.2.3
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.3.0
      - pytorch-lightning==2.5.2
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - rdkit==2024.3.6
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==14.0.0
      - rotary-emb==0.5.2
      - rpds-py==0.24.0
      - safe-mol==0.1.13
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.13.1
      - seaborn==0.13.2
      - selfies==2.2.0
      - send2trash==1.8.3
      - sentry-sdk==2.29.1
      - setproctitle==1.3.6
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - sparse==0.15.5
      - sqlalchemy==2.0.40
      - stack-data==0.6.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.21.1
      - tomli==2.2.1
      - torch==2.6.0+cu124
      - torchaudio==2.6.0+cu124
      - torchmetrics==1.7.3
      - torchvision==0.21.0+cu124
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - transformers==4.51.3
      - triton==3.2.0
      - typer==0.15.4
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.13.2
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - unimol-tools==0.1.4.post1
      - universal-pathlib==0.2.6
      - uri-template==1.3.0
      - urllib3==2.4.0
      - wandb==0.19.11
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xformers==0.0.29.post2
      - xxhash==3.5.0
      - yarl==1.20.0
      - zipp==3.21.0
prefix: /home/user/miniconda3/envs/Spec2Mol
